
version: "3.9"

services:

  db:
    image: mysql
    container_name: mysql-1
    environment:
      MYSQL_DATABASE: 'countries_db'
      MYSQL_USER: 'faruk'
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_PASSWORD: '12345'
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - '3307:3306'

  questionApp-be:
    image: question-app-be
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/countries_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Turkey&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - '8083:8083'
    depends_on:
      - db

networks:
  questionApp-mysql:
