spring:
  config:
    activate:
      on-profile: prod
  application:
    name: countries-rest-api
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        jdbc.batch_size: 20
        cache.use_query_cache: false
        cache.use_second_level_cache: false
        cache.use_structured_entries: false
        cache.use_minimal_puts: false
